name: Pre merge checks

on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  Lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade black
    - name: Lint with Black
      run: |
        pip install black
        black . --check
        
  Unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install PyGithub
        python -m pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
    - name: Run unit tests
      run: |
        cd scraper
        python -m unittest discover tests
